### ISSUE TITLE
Jar builds?

### ISSUE THREAD

**Issue by BigGuyBlue** [Legacy-Fabric/fabric-loader-1.8.9#5]
I think u should try travis ci

**Comment by BoogieMonster1O1** [comment]
> I think u should try travis ci

we already have github actions

**Comment by BoogieMonster1O1** [comment]
for builds, please use the maven http://dl.bintray.com/legacy-fabric/Legacy-Fabric-Maven/net/fabricmc/fabric-loader-1.8.9/

**Comment by BigGuyBlue** [comment]
> for builds, please use the maven http://dl.bintray.com/legacy-fabric/Legacy-Fabric-Maven/net/fabricmc/fabric-loader-1.8.9/

Thanks for respond!
